<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{attribute} can contain only letters, numbers, hyphen, and underscore.' => '',
    '{appname} Robot' => '',
    'Account activation for {appname}' => '',
    'Account recovery for {appname}' => '',
    'Error creating the superuser. Ensure you have the right database permissions.' => '',
    'The user module has been successfully installed. You have been automatically logged in as the superuser (username: {username}).' => '',
    'The installation access code entered is incorrect.' => '',
    'You have not setup a valid class for your user component in your application configuration file. The class must extend {classValid}. Class currently set: {classSet}.' => '',
    'Install Access Code' => '',
    'Username' => '',
    'Password' => '',
    'New Password' => '',
    'Remember Me' => '',
    'Confirm Password' => '',
    'Email' => '',
    'Auth Key' => '',
    'Activation Key' => '',
    'Reset Key' => '',
    'Status' => '',
    'Created On' => '',
    'Updated On' => '',
    'Last Login IP' => '',
    'Last Login On' => '',
    'Password Reset On' => '',
    'Password Fail Attempts' => '',
    'Welcome to {page} module' => '',
    'Installation' => '',
    'Proceed' => ''
];
